### ISSUE TITLE
On this way(Write to Stream), how to set correct order of waves?

### ISSUE THREAD

**Issue by cshijiel** [Migushthe2nd/MsEdgeTTS#1]

**Comment by Migushthe2nd** [comment]
By waves, do you mean frequency as in KHz?

**Comment by Migushthe2nd** [comment]
If you want to change the output format (https://github.com/Migushthe2nd/MsEdgeTTS/blob/main/src/OUTPUT_FORMAT.ts), you have to call `setMetadata` https://github.com/Migushthe2nd/MsEdgeTTS/blob/6cf68beccf42b6167bfe1a5d1103e09be2c02199/src/index.ts#L116
