### ISSUE TITLE
RIFF_16KHZ_16BIT_MONO_PCM cannot generate WAV format files

### ISSUE THREAD

**Issue by qingfengmy** [Migushthe2nd/MsEdgeTTS#10]
```
import {MsEdgeTTS, OUTPUT_FORMAT} from "msedge-tts";

(async () => {
    const tts = new MsEdgeTTS();
    await tts.setMetadata("en-US-AriaNeural", OUTPUT_FORMAT.RIFF_16KHZ_16BIT_MONO_PCM);
    const filePath = await tts.toFile("./wav.wav", "Hi, how are you?");  
})();
```
The format RIFF_16KHZ_16BIT_MONO_PCM does not produce WAV files

**Comment by Migushthe2nd** [comment]
It seems the edge api is limited to three audio formats. See the updated https://github.com/Migushthe2nd/MsEdgeTTS/blob/f83089b4ac2ccebab78e64702c1d062e33443e0e/src/OUTPUT_FORMAT.ts for the formats. I've published a new version.
