### ISSUE TITLE
Reserved Characters in SSML

### ISSUE THREAD

**Issue by yacine-bens** [Migushthe2nd/MsEdgeTTS#12]
If the text contains reserved characters (<>&"') it won't work. Using a simple escape function solves the issue:
![image](https://github.com/Migushthe2nd/MsEdgeTTS/assets/82149396/d75d136e-5210-42dc-ba77-702855bda3e7)
![image](https://github.com/Migushthe2nd/MsEdgeTTS/assets/82149396/aecad305-2839-4c1b-b2bc-2306ccc3fe4a)

**Comment by Migushthe2nd** [comment]
Thanks! As mentioned in the README I recommend you use an xml sanitizer/escape library. I see that it would be more logical to include this functionality in this library itself (but not in the 'raw' methods)

**Comment by yacine-bens** [comment]
Oh you're right! I didn't notice that in the README. Thanks.
