### ISSUE TITLE
Readme need to be fix

### ISSUE THREAD

**Issue by Xkipper** [Migushthe2nd/MsEdgeTTS#2]
Hi. 
The info to use `MsEdgeTTS.OUTPUT_FORMATS.` throw typeof error. After update `OUTPUT_FORMATS` renamed `OUTPUT_FORMAT`.

_Offtopic:
 Could add the limits to usage MsEdgeTTS? I mean: How many words support into a text?
 Could make a Google neural TTS module? (without apiKey)_

**Comment by Migushthe2nd** [comment]
Thanks I'll fix the `OUTPUT_FORMAT` references. 
Tbh, I'm not sure what the limit is. 
And idk about the Google API. Do you know a place it is used?

**Comment by Xkipper** [comment]
> And idk about the Google API. Do you know where it is used so I can reverse engineer it?

I mean that:
https://cloud.google.com/text-to-speech/?hl=es

**Comment by Migushthe2nd** [comment]
Yes but for that you would need an actual API key. I assumed that's what you were trying to avoid

**Comment by Migushthe2nd** [comment]
Fixed by a13022380ea6cf4beec70ca797ee01d5bd32d117
