### ISSUE TITLE
Not able fine-tune anymore

### ISSUE THREAD

**Issue by tanchekwei** [Migushthe2nd/MsEdgeTTS#3]
No audio return from the API when sending with those tags to fine-tune pitch, pronunciation, speaking rate, etc.

Text without any adjustment will still work fine.

**Comment by tanchekwei** [comment]
I have switched to using the actual Azure API

There is a free tier, fortunately.

https://github.com/Microsoft/cognitive-services-speech-sdk-js

**Comment by Migushthe2nd** [comment]
Could you give an example call with an input string?

**Comment by tanchekwei** [comment]
Try:

`Sometimes somebody will bring something that you <prosody rate="-51.00%">really </prosody>like.` <- Not ok

`Sometimes somebody will bring something that you like.` <- Ok

**Comment by Migushthe2nd** [comment]
Long delay, but ran into this myself. The two examples you gave seem to work, however, any fine-tuning using the `mstts` tags indeed does not work
```xml
// does not work
Hi how are you<mstts:silence type="Sentenceboundary" value="150ms"/>
```

```xml
// works fine
Hi how are you
```

I have tried to figure out a way around this, but there seems to be a new whitelist in place that only allows the structure `speak (1) > voice (1) > prosody (>=0)`.
