### ISSUE TITLE
no browser support ?

### ISSUE THREAD

**Issue by Tucsky** [Migushthe2nd/MsEdgeTTS#4]
First of all thank you for this great tts lib it's one the best (free) I've seen so far 👍🏼 

I'm trying to use it from the browser but it does not work.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/5738336/180530780-bf550c65-1114-40d2-847f-d26850d0467a.png">

setMetadata want to create a websocket instance (initClient) and try to access a "client" method which does not exist :/
<img width="295" alt="image" src="https://user-images.githubusercontent.com/5738336/180535548-ab8a95af-416c-40eb-b4d2-84a3ac58a4f5.png">

I have no issue from nodejs. I didn't saw this was a nodejs only package in the doc, just want to make sure it is before moving on

**Comment by Migushthe2nd** [comment]
The module was built for NodeJS. I'll have to check if a browser support is even possible (because of CORS), but don't expect that to happen anytime soon.

**Comment by Tucsky** [comment]
@Migushthe2nd Thanks for the quick answer! I'm not sure either
I looked at your code, the voice endpoint work fine from the browser, the websocket I've not been able to open a connection yet 

Then I found this https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/javascript/browser/text-to-speech so I guess it's possible

Did you shared your subscription token in the repo ? I've been using it for 2 days doing multiple tts/min lol
Anyway I'm going to try this quickstart and get my own subscription token as well :)

**Comment by Migushthe2nd** [comment]
The token in the repo is the one Microsoft Edge uses internally. I have never actually tried using it with the official TTS tools, so maybe the token is all you need for unlimited TTS requests. Could you perhaps try that?


________________________________

**Comment by Migushthe2nd** [comment]
I would assume you can't simply use the token. You'll probably also have to use the specific endpoints Edge uses (and this module as well)

**Comment by Migushthe2nd** [comment]
Published a new version which uses the [ws library](https://www.npmjs.com/package/ws) thanks to @guquan-lengyue. Could you try the newest version?

**Comment by yacine-bens** [comment]
Thank you for the library. It works great on Nodejs.
I am trying to use it in a browser extension with the latest version but I'm facing the same issue. The npm page of the ws library says "Note: This module does not work in the browser.".
![image](https://github.com/Migushthe2nd/MsEdgeTTS/assets/82149396/6dab858b-ecb5-4577-b933-6873ba9f893b)

**Comment by Migushthe2nd** [comment]
Thanks for the notice! I've published 1.3.3, which uses the `isomorphic-ws` library instead of just `ws`.

**Comment by yacine-bens** [comment]
Thanks for your reply. I noticed that they mentioned isomorphic-ws  so I tried it and it didn't work. It is mentioned that it has some limitations like the "options" argument in the constructor, so I tried a constructor with only one argument (MsEdgeTTS.SYNTH_URL) and it didn't work.
I tried to use the native browser WebSocket and changed event functions respectively:
![image](https://github.com/Migushthe2nd/MsEdgeTTS/assets/82149396/039dfc8f-1ec6-4c0d-9a90-d6a3d1625c60)
Then I got the error message: "Uncaught TypeError: Cannot read properties of null (reading '1')" in the "onmessage" function, so I changed "message" element to "m.data":
![image](https://github.com/Migushthe2nd/MsEdgeTTS/assets/82149396/f1794a25-3ada-47d4-af0e-b8aa4eb57b28)
Apparently this is not the right fix as I'm still getting the error, along with another that says "process is not defined"
![image](https://github.com/Migushthe2nd/MsEdgeTTS/assets/82149396/291f7e67-07ae-4fcc-b916-3a98085fe151)

**Comment by yacine-bens** [comment]
The "process is not defined" error has to do with Webpack 5 which is unrelated to this library. And the other issue is that the WebSocket browser library is different from Nodejs, so I would have to edit the functions to be able to read ws data on the browser. I'll post the final result when I come up with a fully functional version :)

**Comment by Migushthe2nd** [comment]
@yacine-bens can you confirm the latest version works in the browser expected?

**Comment by yacine-bens** [comment]
Sorry for the late response. Yes, it's working perfectly. I made a simple Chrome extension using it. 
https://github.com/yacine-bens/MsEdgeTTS-chrome-extension
