### ISSUE TITLE
reuse a wss connection

### ISSUE THREAD

**Issue by fastfading** [Migushthe2nd/MsEdgeTTS#6]
How to reuse a wss connection?
It takes a lot of time to connect to wss every time.
Is it possible to use the same wss for multiple tts requests?

**Comment by Migushthe2nd** [comment]
The connection should stay open by default, although Microsoft closes the connection after some time it no requests are made.

**Comment by fastfading** [comment]
have you try  send 2  text    in one wss connection?
it seems it does not get response.  and after while , connection closed

**Comment by Migushthe2nd** [comment]
Hi, could you try out the latest version of the module? The websocket library was changed so this issue might have been resolved.
